### ISSUE TITLE
2 years-old

### ISSUE THREAD

**Issue by MathGon** [bosborne/Bio-DB-Das-BioSQL#1]
Hi,

i this still working with last releases of JBrowse and Biosql?

Thanks

**Comment by bosborne** [comment]
I'm not sure, I have not kept up with the JBrowse. It did work roughly a year ago. I'll update the documentation to indicate this.

**Comment by MathGon** [comment]
I used to store data in BioSQL and I'm starting a new project. Tell me if you have any advice to give me about alternative databases and  genome brower ;)

**Comment by bosborne** [comment]
I would take a look at the new “Web” version of IGV:

https://github.com/igvteam/igv.js

**Comment by bosborne** [comment]
Looks like MathGon may have used igv-web.
